/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controll.Validador;

/**
 *
 * @author Nicolas
 */
public class TelaVenda extends javax.swing.JFrame {

    /**
     * Creates new form TelaVenda
     */
    public TelaVenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_MenuEsquerdo = new javax.swing.JPanel();
        pnl_Logo = new javax.swing.JPanel();
        btn_CadastroCliente = new javax.swing.JButton();
        btn_ClientesCadastrados = new javax.swing.JButton();
        btn_Estoque = new javax.swing.JButton();
        btn_Relatorio = new javax.swing.JButton();
        pnl_Venda = new javax.swing.JPanel();
        txt_CPF = new javax.swing.JTextField();
        btn_Buscar = new javax.swing.JButton();
        txt_CodigoProduto = new javax.swing.JTextField();
        txt_Quantidade = new javax.swing.JTextField();
        btn_Remover = new javax.swing.JButton();
        btn_Adicionar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Produtos = new javax.swing.JTable();
        lbl_Descricao = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txt_ValorTotal = new javax.swing.JTextField();
        btn_Cancelar = new javax.swing.JButton();
        btn_Concluir = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Venda");

        pnl_MenuEsquerdo.setBackground(new java.awt.Color(87, 87, 87));
        pnl_MenuEsquerdo.setPreferredSize(new java.awt.Dimension(179, 512));

        pnl_Logo.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));

        javax.swing.GroupLayout pnl_LogoLayout = new javax.swing.GroupLayout(pnl_Logo);
        pnl_Logo.setLayout(pnl_LogoLayout);
        pnl_LogoLayout.setHorizontalGroup(
            pnl_LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnl_LogoLayout.setVerticalGroup(
            pnl_LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );

        btn_CadastroCliente.setText("CADASTRO  CLIENTE");
        btn_CadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CadastroClienteActionPerformed(evt);
            }
        });

        btn_ClientesCadastrados.setText("CLIENTES");
        btn_ClientesCadastrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClientesCadastradosActionPerformed(evt);
            }
        });

        btn_Estoque.setText("ESTOQUE");
        btn_Estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EstoqueActionPerformed(evt);
            }
        });

        btn_Relatorio.setText("RELATORIO");
        btn_Relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_MenuEsquerdoLayout = new javax.swing.GroupLayout(pnl_MenuEsquerdo);
        pnl_MenuEsquerdo.setLayout(pnl_MenuEsquerdoLayout);
        pnl_MenuEsquerdoLayout.setHorizontalGroup(
            pnl_MenuEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_MenuEsquerdoLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(pnl_MenuEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_Estoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_Logo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_CadastroCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_ClientesCadastrados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Relatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        pnl_MenuEsquerdoLayout.setVerticalGroup(
            pnl_MenuEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_MenuEsquerdoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(pnl_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btn_CadastroCliente)
                .addGap(60, 60, 60)
                .addComponent(btn_ClientesCadastrados)
                .addGap(60, 60, 60)
                .addComponent(btn_Estoque)
                .addGap(60, 60, 60)
                .addComponent(btn_Relatorio)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pnl_Venda.setBackground(new java.awt.Color(250, 250, 250));
        pnl_Venda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl_Venda.setPreferredSize(new java.awt.Dimension(540, 100));

        txt_CPF.setForeground(java.awt.Color.lightGray);
        txt_CPF.setText("CPF");
        txt_CPF.setName("CPF"); // NOI18N
        txt_CPF.setPreferredSize(new java.awt.Dimension(276, 27));
        txt_CPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_CPD_focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_CPF_focusLost(evt);
            }
        });
        txt_CPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CPFActionPerformed(evt);
            }
        });
        txt_CPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_CPF_keyTyped(evt);
            }
        });

        btn_Buscar.setText("BUSCAR");
        btn_Buscar.setPreferredSize(new java.awt.Dimension(158, 27));

        txt_CodigoProduto.setForeground(java.awt.Color.lightGray);
        txt_CodigoProduto.setText("CodigoProduto");
        txt_CodigoProduto.setName("CodigoProduto"); // NOI18N
        txt_CodigoProduto.setPreferredSize(new java.awt.Dimension(276, 41));
        txt_CodigoProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_CodigoProduto_focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_CodigoProduto_focusLost(evt);
            }
        });
        txt_CodigoProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_CodigoProduto_keyTyped(evt);
            }
        });

        txt_Quantidade.setForeground(java.awt.Color.lightGray);
        txt_Quantidade.setText("Quantidade");
        txt_Quantidade.setName("Quantidade"); // NOI18N
        txt_Quantidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_Quantidade_focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_Quantidade_focusLost(evt);
            }
        });
        txt_Quantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_Quantidade_keyTyped(evt);
            }
        });

        btn_Remover.setText("REMOVER");
        btn_Remover.setPreferredSize(new java.awt.Dimension(182, 18));

        btn_Adicionar.setText("ADICIONAR");
        btn_Adicionar.setPreferredSize(new java.awt.Dimension(75, 18));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(477, 184));

        tbl_Produtos.setAutoCreateRowSorter(true);
        tbl_Produtos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Valor", "Quantidade", "Total"
            }
        ));
        tbl_Produtos.setPreferredSize(new java.awt.Dimension(477, 184));
        jScrollPane1.setViewportView(tbl_Produtos);

        javax.swing.GroupLayout pnl_VendaLayout = new javax.swing.GroupLayout(pnl_Venda);
        pnl_Venda.setLayout(pnl_VendaLayout);
        pnl_VendaLayout.setHorizontalGroup(
            pnl_VendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_VendaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnl_VendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnl_VendaLayout.createSequentialGroup()
                        .addGroup(pnl_VendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_Remover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnl_VendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_CodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43)
                        .addGroup(pnl_VendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_Buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_Quantidade)
                            .addComponent(btn_Adicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnl_VendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl_Descricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        pnl_VendaLayout.setVerticalGroup(
            pnl_VendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_VendaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnl_VendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(pnl_VendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_CodigoProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_Quantidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_VendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_Remover, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(btn_Adicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(lbl_Descricao)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        txt_CPF.getAccessibleContext().setAccessibleName("CPF");

        jPanel3.setBackground(new java.awt.Color(146, 146, 146));

        txt_ValorTotal.setEditable(false);
        txt_ValorTotal.setForeground(java.awt.Color.lightGray);
        txt_ValorTotal.setText("VALOR_TOTAL");
        txt_ValorTotal.setPreferredSize(new java.awt.Dimension(252, 42));

        btn_Cancelar.setText("CANCELAR");
        btn_Cancelar.setPreferredSize(new java.awt.Dimension(225, 18));

        btn_Concluir.setText("CONCLUIR");
        btn_Concluir.setPreferredSize(new java.awt.Dimension(225, 18));

        jComboBox1.setForeground(java.awt.Color.lightGray);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PAGAMENTO", "CREDITO", "DEBITO", "DINHEIRO" }));
        jComboBox1.setPreferredSize(new java.awt.Dimension(126, 42));

        jComboBox2.setForeground(java.awt.Color.lightGray);
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PARCELAS", "1X", "2X", "3X", "4X", "5X", "6X" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Concluir, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_ValorTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox2))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Concluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_MenuEsquerdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_Venda, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_MenuEsquerdo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_Venda, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CadastroClienteActionPerformed
        // TODO add your handling code here:
        TelaCadastroCliente Cdt_Cliente = new TelaCadastroCliente();
        Cdt_Cliente.setVisible(true);
    }//GEN-LAST:event_btn_CadastroClienteActionPerformed

    private void txt_CPD_focusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_CPD_focusGained
        // TODO add your handling code here:
        Validador.verificaVazio(txt_CPF, lbl_Descricao);
    }//GEN-LAST:event_txt_CPD_focusGained

    private void txt_CPF_focusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_CPF_focusLost
        // TODO add your handling code here:
        Validador.verificaVazio(txt_CPF, lbl_Descricao);
    }//GEN-LAST:event_txt_CPF_focusLost

    private void txt_CodigoProduto_focusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_CodigoProduto_focusGained
        // TODO add your handling code here:
        Validador.verificaVazio(txt_CodigoProduto, lbl_Descricao);
    }//GEN-LAST:event_txt_CodigoProduto_focusGained

    private void txt_CodigoProduto_focusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_CodigoProduto_focusLost
        // TODO add your handling code here:
        Validador.verificaVazio(txt_CodigoProduto, lbl_Descricao);
    }//GEN-LAST:event_txt_CodigoProduto_focusLost

    private void txt_Quantidade_focusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_Quantidade_focusGained
        // TODO add your handling code here:
        Validador.verificaVazio(txt_Quantidade, lbl_Descricao);
    }//GEN-LAST:event_txt_Quantidade_focusGained

    private void txt_Quantidade_focusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_Quantidade_focusLost
        // TODO add your handling code here:
        Validador.verificaVazio(txt_Quantidade, lbl_Descricao);
    }//GEN-LAST:event_txt_Quantidade_focusLost

    private void txt_CPF_keyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CPF_keyTyped
        // TODO add your handling code here:
        Validador.verificaCPF(evt, lbl_Descricao, txt_CPF);
    }//GEN-LAST:event_txt_CPF_keyTyped

    private void txt_CodigoProduto_keyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CodigoProduto_keyTyped
        // TODO add your handling code here:
        Validador.verificaCodigoBarra(evt, lbl_Descricao, txt_CodigoProduto);
    }//GEN-LAST:event_txt_CodigoProduto_keyTyped

    private void txt_Quantidade_keyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Quantidade_keyTyped
        // TODO add your handling code here:
        Validador.verificaNumero(evt, lbl_Descricao, txt_Quantidade);
    }//GEN-LAST:event_txt_Quantidade_keyTyped

    private void btn_EstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EstoqueActionPerformed
        // TODO add your handling code here:
        TelaEstoque Estoque = new TelaEstoque();
        Estoque.setVisible(true);
    }//GEN-LAST:event_btn_EstoqueActionPerformed

    private void btn_ClientesCadastradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClientesCadastradosActionPerformed
        // TODO add your handling code here:
        TelaClientes Clientes = new TelaClientes();
        Clientes.setVisible(true);
    }//GEN-LAST:event_btn_ClientesCadastradosActionPerformed

    private void btn_RelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RelatorioActionPerformed
        // TODO add your handling code here:
        TelaRelatorio Relatorio = new TelaRelatorio();
        Relatorio.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_RelatorioActionPerformed

    private void txt_CPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CPFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Adicionar;
    private javax.swing.JButton btn_Buscar;
    private javax.swing.JButton btn_CadastroCliente;
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JButton btn_ClientesCadastrados;
    private javax.swing.JButton btn_Concluir;
    private javax.swing.JButton btn_Estoque;
    private javax.swing.JButton btn_Relatorio;
    private javax.swing.JButton btn_Remover;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Descricao;
    private javax.swing.JPanel pnl_Logo;
    private javax.swing.JPanel pnl_MenuEsquerdo;
    private javax.swing.JPanel pnl_Venda;
    private javax.swing.JTable tbl_Produtos;
    private javax.swing.JTextField txt_CPF;
    private javax.swing.JTextField txt_CodigoProduto;
    private javax.swing.JTextField txt_Quantidade;
    private javax.swing.JTextField txt_ValorTotal;
    // End of variables declaration//GEN-END:variables
}
