/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controll.Cliente;
import Controll.Validador;
import DAO.ClienteDAO;
import java.awt.Color;
import java.util.Date;
import javax.swing.JOptionPane;


/**
 *
 * @author Nicolas
 */
public class TelaCadastroCliente extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroCliente
     */
    
    Cliente pessoa = null;
    
    public TelaCadastroCliente() {
        initComponents();
    }
    
    public TelaCadastroCliente(Cliente obj) {
        initComponents();
        this.pessoa = obj;

        txt_Nome.setText(String.valueOf(pessoa.getNome()));
        txt_CPF.setText(String.valueOf(pessoa.getCPF()));
        txt_CEP.setText(String.valueOf(pessoa.getCEP()));
        txt_Cidade.setText(String.valueOf(pessoa.getCidade()));
        txt_Estado.setText(String.valueOf(pessoa.getEstado()));
        txt_Rua.setText(String.valueOf(pessoa.getRua()));
        txt_Numero.setText(String.valueOf(pessoa.getNumero()));
        txt_Telefone.setText(String.valueOf(pessoa.getTelefone()));
        txt_Email.setText(String.valueOf(pessoa.getEmail()));
        cbx_Sexo.setSelectedItem(String.valueOf(pessoa.getGenero()));
        cbx_EstadoCivil.setSelectedItem(String.valueOf(pessoa.getEstadoCivil()));
        txt_DataNascimento.setDate(pessoa.getDatanascimento());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_Nome = new javax.swing.JTextField();
        txt_CPF = new javax.swing.JTextField();
        btn_Buscar = new javax.swing.JButton();
        txt_CEP = new javax.swing.JTextField();
        txt_Estado = new javax.swing.JTextField();
        txt_Cidade = new javax.swing.JTextField();
        txt_Rua = new javax.swing.JTextField();
        txt_Numero = new javax.swing.JTextField();
        txt_Telefone = new javax.swing.JTextField();
        txt_Email = new javax.swing.JTextField();
        cbx_Sexo = new javax.swing.JComboBox<>();
        cbx_EstadoCivil = new javax.swing.JComboBox<>();
        lbl_Descricao = new javax.swing.JLabel();
        btn_Cancelar = new javax.swing.JButton();
        btn_Confirmar = new javax.swing.JButton();
        txt_DataNascimento = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CadastroCliente");

        txt_Nome.setBackground(new java.awt.Color(255, 255, 204));
        txt_Nome.setForeground(java.awt.Color.lightGray);
        txt_Nome.setText("NomeUsuario");
        txt_Nome.setName("NomeUsuario"); // NOI18N
        txt_Nome.setPreferredSize(new java.awt.Dimension(396, 30));
        txt_Nome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_Nome_focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_Nome_focusLost(evt);
            }
        });
        txt_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NomeActionPerformed(evt);
            }
        });

        txt_CPF.setBackground(new java.awt.Color(255, 255, 204));
        txt_CPF.setForeground(java.awt.Color.lightGray);
        txt_CPF.setText("CPF");
        txt_CPF.setName("CPF"); // NOI18N
        txt_CPF.setPreferredSize(new java.awt.Dimension(112, 30));
        txt_CPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_CPF_focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_CPF_focusLost(evt);
            }
        });
        txt_CPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CPFActionPerformed(evt);
            }
        });
        txt_CPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_CPF_keyTyped(evt);
            }
        });

        btn_Buscar.setText("BUSCAR");
        btn_Buscar.setPreferredSize(new java.awt.Dimension(174, 30));

        txt_CEP.setBackground(new java.awt.Color(255, 255, 204));
        txt_CEP.setForeground(java.awt.Color.lightGray);
        txt_CEP.setText("CEP");
        txt_CEP.setName("CEP"); // NOI18N
        txt_CEP.setPreferredSize(new java.awt.Dimension(85, 30));
        txt_CEP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_CEP_focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_CEP_focusLost(evt);
            }
        });
        txt_CEP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_CEP_keyTyped(evt);
            }
        });

        txt_Estado.setBackground(new java.awt.Color(255, 255, 204));
        txt_Estado.setForeground(java.awt.Color.lightGray);
        txt_Estado.setText("Estado");
        txt_Estado.setName("Estado"); // NOI18N
        txt_Estado.setPreferredSize(new java.awt.Dimension(158, 30));
        txt_Estado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_Estado_focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_Estado_focusLost(evt);
            }
        });

        txt_Cidade.setBackground(new java.awt.Color(255, 255, 204));
        txt_Cidade.setForeground(java.awt.Color.lightGray);
        txt_Cidade.setText("Cidade");
        txt_Cidade.setName("Cidade"); // NOI18N
        txt_Cidade.setPreferredSize(new java.awt.Dimension(225, 30));
        txt_Cidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_Cidade_focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_Cidade_focusLost(evt);
            }
        });

        txt_Rua.setBackground(new java.awt.Color(255, 255, 204));
        txt_Rua.setForeground(java.awt.Color.lightGray);
        txt_Rua.setText("Rua");
        txt_Rua.setName("Rua"); // NOI18N
        txt_Rua.setPreferredSize(new java.awt.Dimension(250, 30));
        txt_Rua.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_Rua_focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_Rua_focusLost(evt);
            }
        });

        txt_Numero.setBackground(new java.awt.Color(255, 255, 204));
        txt_Numero.setForeground(java.awt.Color.lightGray);
        txt_Numero.setText("Numero");
        txt_Numero.setName("Numero"); // NOI18N
        txt_Numero.setPreferredSize(new java.awt.Dimension(130, 30));
        txt_Numero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_Numero_focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_Numero_focusLost(evt);
            }
        });
        txt_Numero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_Numero_keyTyped(evt);
            }
        });

        txt_Telefone.setForeground(java.awt.Color.lightGray);
        txt_Telefone.setText("Telefone");
        txt_Telefone.setName("Telefone"); // NOI18N
        txt_Telefone.setPreferredSize(new java.awt.Dimension(241, 30));
        txt_Telefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_Telefone_focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_Telefone_focusLost(evt);
            }
        });
        txt_Telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TelefoneActionPerformed(evt);
            }
        });
        txt_Telefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_Telefone_keyTyped(evt);
            }
        });

        txt_Email.setBackground(new java.awt.Color(255, 255, 204));
        txt_Email.setForeground(java.awt.Color.lightGray);
        txt_Email.setText("EMAIL");
        txt_Email.setName("EMAIL"); // NOI18N
        txt_Email.setPreferredSize(new java.awt.Dimension(396, 30));
        txt_Email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_Email_focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_Email_focusLost(evt);
            }
        });

        cbx_Sexo.setBackground(new java.awt.Color(255, 255, 204));
        cbx_Sexo.setForeground(java.awt.Color.lightGray);
        cbx_Sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GENERO", "MASCULINO", "FEMININO", "NAO_BINARIO", "HELICOPTERO_DE_COMBATE" }));
        cbx_Sexo.setPreferredSize(new java.awt.Dimension(142, 30));
        cbx_Sexo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbx_Sexo_focusLost(evt);
            }
        });

        cbx_EstadoCivil.setForeground(java.awt.Color.lightGray);
        cbx_EstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ESTADO_CIVIL", "SOLTEIRO", "CASADO", "DIVORCIADO", "VIUVO" }));
        cbx_EstadoCivil.setPreferredSize(new java.awt.Dimension(216, 30));

        lbl_Descricao.setDoubleBuffered(true);
        lbl_Descricao.setPreferredSize(new java.awt.Dimension(192, 30));

        btn_Cancelar.setText("CANCELAR");
        btn_Cancelar.setPreferredSize(new java.awt.Dimension(180, 30));
        btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarActionPerformed(evt);
            }
        });

        btn_Confirmar.setText("CONFIRMAR");
        btn_Confirmar.setPreferredSize(new java.awt.Dimension(180, 30));
        btn_Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ConfirmarActionPerformed(evt);
            }
        });

        txt_DataNascimento.setDateFormatString("dd/MM/yyyy");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_Rua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(txt_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cbx_Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbx_EstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_Email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_CEP, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_DataNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Confirmar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Descricao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(txt_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_CEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Rua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txt_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_EstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_Descricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_DataNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_Nome_focusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_Nome_focusGained
        // TODO add your handling code here:
        Validador.verificaVazio(txt_Nome, lbl_Descricao);
    }//GEN-LAST:event_txt_Nome_focusGained

    private void txt_Nome_focusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_Nome_focusLost
        // TODO add your handling code here:
        Validador.verificaVazio(txt_Nome, lbl_Descricao);
    }//GEN-LAST:event_txt_Nome_focusLost

    private void txt_CPF_focusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_CPF_focusGained
        // TODO add your handling code here:
        Validador.verificaVazio(txt_CPF, lbl_Descricao);
    }//GEN-LAST:event_txt_CPF_focusGained

    private void txt_CPF_focusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_CPF_focusLost
        // TODO add your handling code here:
        Validador.verificaVazio(txt_CPF, lbl_Descricao);
    }//GEN-LAST:event_txt_CPF_focusLost

    private void txt_CEP_focusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_CEP_focusGained
        // TODO add your handling code here:
        Validador.verificaVazio(txt_CEP, lbl_Descricao);
    }//GEN-LAST:event_txt_CEP_focusGained

    private void txt_CEP_focusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_CEP_focusLost
        // TODO add your handling code here:
        Validador.verificaVazio(txt_CEP, lbl_Descricao);
    }//GEN-LAST:event_txt_CEP_focusLost

    private void txt_Cidade_focusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_Cidade_focusGained
        // TODO add your handling code here:
        Validador.verificaVazio(txt_Cidade, lbl_Descricao);
    }//GEN-LAST:event_txt_Cidade_focusGained

    private void txt_Cidade_focusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_Cidade_focusLost
        // TODO add your handling code here:
        Validador.verificaVazio(txt_Cidade, lbl_Descricao);
    }//GEN-LAST:event_txt_Cidade_focusLost

    private void txt_Estado_focusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_Estado_focusGained
        // TODO add your handling code here:
        Validador.verificaVazio(txt_Estado, lbl_Descricao);
    }//GEN-LAST:event_txt_Estado_focusGained

    private void txt_Estado_focusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_Estado_focusLost
        // TODO add your handling code here:
        Validador.verificaVazio(txt_Estado, lbl_Descricao);
    }//GEN-LAST:event_txt_Estado_focusLost

    private void txt_Rua_focusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_Rua_focusGained
        // TODO add your handling code here:
        Validador.verificaVazio(txt_Rua, lbl_Descricao);
    }//GEN-LAST:event_txt_Rua_focusGained

    private void txt_Rua_focusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_Rua_focusLost
        // TODO add your handling code here:
        Validador.verificaVazio(txt_Rua, lbl_Descricao);
    }//GEN-LAST:event_txt_Rua_focusLost

    private void txt_Numero_focusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_Numero_focusGained
        // TODO add your handling code here:
        Validador.verificaVazio(txt_Numero, lbl_Descricao);
    }//GEN-LAST:event_txt_Numero_focusGained

    private void txt_Numero_focusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_Numero_focusLost
        // TODO add your handling code here:
        Validador.verificaVazio(txt_Numero, lbl_Descricao);
    }//GEN-LAST:event_txt_Numero_focusLost

    private void txt_Telefone_focusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_Telefone_focusGained
        // TODO add your handling code here:
        Validador.verificaVazio(txt_Telefone, lbl_Descricao);
    }//GEN-LAST:event_txt_Telefone_focusGained

    private void txt_Email_focusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_Email_focusGained
        // TODO add your handling code here:
        Validador.verificaVazio(txt_Email, lbl_Descricao);
    }//GEN-LAST:event_txt_Email_focusGained

    private void txt_Telefone_focusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_Telefone_focusLost
        // TODO add your handling code here:
        Validador.verificaVazio(txt_Telefone, lbl_Descricao);
    }//GEN-LAST:event_txt_Telefone_focusLost

    private void txt_Email_focusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_Email_focusLost
        // TODO add your handling code here:
        Validador.verificaVazio(txt_Email, lbl_Descricao);
    }//GEN-LAST:event_txt_Email_focusLost

    private void cbx_Sexo_focusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbx_Sexo_focusLost
        // TODO add your handling code here:
        if(cbx_Sexo.getSelectedItem().toString().trim().equals("GENERO")){
            cbx_Sexo.setForeground(Color.lightGray);
        }else{
            cbx_Sexo.setForeground(Color.black);
        }
    }//GEN-LAST:event_cbx_Sexo_focusLost

    private void txt_CPF_keyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CPF_keyTyped
        // TODO add your handling code here:
        Validador.verificaCPF(evt, lbl_Descricao, txt_CPF);
    }//GEN-LAST:event_txt_CPF_keyTyped

    private void txt_CEP_keyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CEP_keyTyped
        // TODO add your handling code here:
        Validador.verificaCEP(evt, lbl_Descricao, txt_CEP);
    }//GEN-LAST:event_txt_CEP_keyTyped

    private void txt_Numero_keyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Numero_keyTyped
        // TODO add your handling code here:
        Validador.verificaNumero(evt, lbl_Descricao, txt_Numero);
    }//GEN-LAST:event_txt_Numero_keyTyped

    private void txt_Telefone_keyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Telefone_keyTyped
        // TODO add your handling code here:
        Validador.verificaTelefone(evt, lbl_Descricao, txt_Telefone);
    }//GEN-LAST:event_txt_Telefone_keyTyped

    private void btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_CancelarActionPerformed

    private void btn_ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ConfirmarActionPerformed
        // TODO add your handling code here:
        Validador.verificaObrigatorioCliente(txt_Nome, txt_CPF, txt_CEP, txt_Cidade,
                                txt_Estado, txt_Rua, txt_Numero, txt_Email, cbx_Sexo);
        
        if (pessoa != null) {
            String nome = txt_Nome.getText().trim();
            String cpf = txt_CPF.getText().trim();
            String cep = txt_CEP.getText().trim();
            String cidade = txt_Cidade.getText().trim();
            String estado = txt_Estado.getText().trim();
            String rua = txt_Rua.getText().trim();
            int numero = Integer.parseInt(txt_Numero.getText().trim());
            String telefone = (txt_Telefone.getText().trim());
            String genero = cbx_Sexo.getSelectedItem().toString().trim();
            String estadoCivil = cbx_EstadoCivil.getSelectedItem().toString().trim();
            Date dataNascimento = txt_DataNascimento.getDate();
            
            
            
            pessoa.setNome(nome);
            pessoa.setCPF(cpf);
            pessoa.setCEP(cep);
            pessoa.setCidade(cidade);
            pessoa.setEstado(estado);
            pessoa.setRua(rua);
            pessoa.setNumero(numero);
            pessoa.setTelefone(telefone);
            pessoa.setGenero(genero);
            pessoa.setEstadoCivil(estadoCivil);
            pessoa.setDatanascimento(dataNascimento);
            
            
            boolean retorno = ClienteDAO.alterar(pessoa);
            
            if (retorno) {
                JOptionPane.showMessageDialog(rootPane, "Sucesso!");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Falha!");
            }
            
        } else {

            //Modo de cadastro:
            // 1 - recupero os dados
            String nome = txt_Nome.getText().trim();
            String cpf = txt_CPF.getText().trim();
            String cep = txt_CEP.getText().trim();
            String cidade = txt_Cidade.getText().trim();
            String estado = txt_Estado.getText().trim();
            String rua = txt_Rua.getText().trim();
            int numero = Integer.parseInt(txt_Numero.getText().trim());
            String telefone = (txt_Telefone.getText().trim());
            String genero = cbx_Sexo.getSelectedItem().toString().trim();
            String estadoCivil = cbx_EstadoCivil.getSelectedItem().toString().trim();
            
            Date dataNascimento = txt_DataNascimento.getDate();

            // 2 - crio o objeto da nota fiscal e passo os valores
            Cliente novoCliente = new Cliente(nome, cpf, cep, cidade, estado, rua, rua, estadoCivil, genero, numero, telefone, dataNascimento);

            // 3 - passar o objeto para o banco
            boolean retorno = ClienteDAO.salvar(novoCliente);

            if (retorno) {
                JOptionPane.showMessageDialog(rootPane, "Sucesso!");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Falha!");
            }
        }
    }//GEN-LAST:event_btn_ConfirmarActionPerformed

    private void txt_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NomeActionPerformed

    private void txt_TelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TelefoneActionPerformed

    private void txt_CPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CPFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Buscar;
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JButton btn_Confirmar;
    private javax.swing.JComboBox<String> cbx_EstadoCivil;
    private javax.swing.JComboBox<String> cbx_Sexo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_Descricao;
    private javax.swing.JTextField txt_CEP;
    private javax.swing.JTextField txt_CPF;
    private javax.swing.JTextField txt_Cidade;
    private com.toedter.calendar.JDateChooser txt_DataNascimento;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_Estado;
    private javax.swing.JTextField txt_Nome;
    private javax.swing.JTextField txt_Numero;
    private javax.swing.JTextField txt_Rua;
    private javax.swing.JTextField txt_Telefone;
    // End of variables declaration//GEN-END:variables
}
