/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controll.Cliente;
import Controll.Validador;
import DAO.ClienteDAO;
import java.sql.Date;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nicolas
 */
public class TelaClientes extends javax.swing.JFrame {

    /**
     * Creates new form TelaClientes
     */
    public TelaClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Voltar = new javax.swing.JButton();
        btn_Buscar = new javax.swing.JButton();
        cbx_BuscarPor = new javax.swing.JComboBox<>();
        txt_CampoBusca = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        lbl_Descricao = new javax.swing.JLabel();
        btn_Editar = new javax.swing.JButton();
        btn_Remover = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clientes");

        btn_Voltar.setText("VOLTAR");
        btn_Voltar.setPreferredSize(new java.awt.Dimension(90, 30));
        btn_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VoltarActionPerformed(evt);
            }
        });

        btn_Buscar.setText("BUSCAR");
        btn_Buscar.setPreferredSize(new java.awt.Dimension(90, 30));
        btn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarActionPerformed(evt);
            }
        });

        cbx_BuscarPor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CPF" }));
        cbx_BuscarPor.setPreferredSize(new java.awt.Dimension(180, 30));

        txt_CampoBusca.setForeground(java.awt.Color.lightGray);
        txt_CampoBusca.setText("cpf");
        txt_CampoBusca.setName("cpf"); // NOI18N
        txt_CampoBusca.setPreferredSize(new java.awt.Dimension(386, 30));
        txt_CampoBusca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_CampoBusca_FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_CampoBusca_FocusLost(evt);
            }
        });
        txt_CampoBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCampoBuscaKeyTyped(evt);
            }
        });

        jScrollPane1.setPreferredSize(new java.awt.Dimension(200, 200));

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "CPF", "CEP", "Cidade", "Estado", "Rua", "NumeroResidencia", "Email", "Telefone", "DataNascimento", "Genero", "EstadoCivil"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblClientes.setToolTipText("");
        tblClientes.setPreferredSize(new java.awt.Dimension(386, 287));
        jScrollPane1.setViewportView(tblClientes);

        lbl_Descricao.setPreferredSize(new java.awt.Dimension(37, 30));

        btn_Editar.setText("EDITAR");
        btn_Editar.setPreferredSize(new java.awt.Dimension(180, 30));
        btn_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditarActionPerformed(evt);
            }
        });

        btn_Remover.setText("REMOVER");
        btn_Remover.setPreferredSize(new java.awt.Dimension(180, 30));
        btn_Remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btn_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Remover, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbx_BuscarPor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lbl_Descricao, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_CampoBusca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_BuscarPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txt_CampoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Remover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarActionPerformed
        // TODO add your handling code here:
        if (txt_CampoBusca.getText().strip().equals("cpf")) {
            atualizarTabela();
        } else {
            String cpfx = txt_CampoBusca.getText().trim();
            ArrayList<Cliente> lstRetorno = ClienteDAO.buscarNumero(cpfx);

            DefaultTableModel modelo = (DefaultTableModel) tblClientes.getModel();

            modelo.setRowCount(0);

            for (Cliente item : lstRetorno) {
                //adicionando uma linha a tabela
                modelo.addRow(new String[]{
                    String.valueOf(item.getNome()),
                    String.valueOf(item.getCPF()),
                    String.valueOf(item.getCEP()),
                    String.valueOf(item.getCidade()),
                    String.valueOf(item.getEstado()),
                    String.valueOf(item.getRua()),
                    String.valueOf(item.getNumero()),
                    String.valueOf(item.getEmail()),
                    String.valueOf(item.getTelefone()),
                    String.valueOf(item.getDatanascimento()),
                    String.valueOf(item.getGenero()),
                    String.valueOf(item.getEstadoCivil()),});
            }
        }
    }//GEN-LAST:event_btn_BuscarActionPerformed

    public void atualizarTabela() {
        //chama a DAO para listar as notas adicionadas
        ArrayList<Cliente> lstRetorno = ClienteDAO.listar();

        //para cada item da lstRetorno adicionio a tabela
        DefaultTableModel modelo = (DefaultTableModel) tblClientes.getModel();

        //Zerar as linhas da tabela
        modelo.setRowCount(0);

        for (Cliente item : lstRetorno) {
            //adicionando uma linha a tabela
            modelo.addRow(new String[]{
                String.valueOf(item.getNome()),
                String.valueOf(item.getCPF()),
                String.valueOf(item.getCEP()),
                String.valueOf(item.getCidade()),
                String.valueOf(item.getEstado()),
                String.valueOf(item.getRua()),
                String.valueOf(item.getNumero()),
                String.valueOf(item.getEmail()),
                String.valueOf(item.getTelefone()),
                String.valueOf(item.getDatanascimento()),
                String.valueOf(item.getGenero()),
                String.valueOf(item.getEstadoCivil()),});
        }
    }

    private void btn_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VoltarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_VoltarActionPerformed

    private void txt_CampoBusca_FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_CampoBusca_FocusGained
        // TODO add your handling code here:
        Validador.verificaVazio(txt_CampoBusca, lbl_Descricao);
    }//GEN-LAST:event_txt_CampoBusca_FocusGained

    private void txt_CampoBusca_FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_CampoBusca_FocusLost
        // TODO add your handling code here:
        Validador.verificaVazio(txt_CampoBusca, lbl_Descricao);
    }//GEN-LAST:event_txt_CampoBusca_FocusLost

    private void btn_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditarActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = tblClientes.getSelectedRow();

        if (linhaSelecionada >= 0) {
            DefaultTableModel modelo = (DefaultTableModel) tblClientes.getModel();

            String nome = modelo.getValueAt(linhaSelecionada, 0).toString();
            String cpf = (modelo.getValueAt(linhaSelecionada, 1).toString());
            String cep = (modelo.getValueAt(linhaSelecionada, 2).toString());
            String cidade = modelo.getValueAt(linhaSelecionada, 3).toString();
            String estado = (modelo.getValueAt(linhaSelecionada, 4).toString());
            String rua = (modelo.getValueAt(linhaSelecionada, 5).toString());
            int numeroResidencia = Integer.parseInt(modelo.getValueAt(linhaSelecionada, 6).toString());
            String email = (modelo.getValueAt(linhaSelecionada, 7).toString());
            String telefone = (modelo.getValueAt(linhaSelecionada, 8).toString());
            Date dataNascimento = Date.valueOf(modelo.getValueAt(linhaSelecionada, 9).toString());
            String genero = (modelo.getValueAt(linhaSelecionada, 10).toString());
            String estadoCivil = (modelo.getValueAt(linhaSelecionada, 11).toString());

            Cliente objAlterar = new Cliente(nome, cpf, cep, cidade, estado, rua, email, estadoCivil, genero, numeroResidencia, telefone, dataNascimento);

            //Mandar objeto para tela de cadastro
            TelaCadastroCliente telaCadastro = new TelaCadastroCliente(objAlterar);
            telaCadastro.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione uma linha!");
        }
    }//GEN-LAST:event_btn_EditarActionPerformed

    private void btn_RemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RemoverActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = tblClientes.getSelectedRow();

        if (linhaSelecionada >= 0) {
            DefaultTableModel modelo = (DefaultTableModel) tblClientes.getModel();

            String cpfx = modelo.getValueAt(linhaSelecionada, 1).toString();

            boolean retorno = ClienteDAO.excluir(cpfx);

            if (retorno) {
                JOptionPane.showMessageDialog(rootPane, "Sucesso!");
                btn_BuscarActionPerformed(evt);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Falha!");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione uma linha!!");
        }
    }//GEN-LAST:event_btn_RemoverActionPerformed

    private void txtCampoBuscaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCampoBuscaKeyTyped
        // TODO add your handling code here:
        Validador.verificaCPF(evt, lbl_Descricao, txt_CampoBusca);
    }//GEN-LAST:event_txtCampoBuscaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Buscar;
    private javax.swing.JButton btn_Editar;
    private javax.swing.JButton btn_Remover;
    private javax.swing.JButton btn_Voltar;
    private javax.swing.JComboBox<String> cbx_BuscarPor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Descricao;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txt_CampoBusca;
    // End of variables declaration//GEN-END:variables
}
