/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controll.Cliente;
import Controll.Produto;
import Controll.Validador;
import DAO.ClienteDAO;
import DAO.ProdutoDAO;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Nicolas
 */
public class TelaCadastroProduto extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroProduto
     */
    Produto prod = null;

    public TelaCadastroProduto() {
        initComponents();
    }

    public TelaCadastroProduto(Produto obj) {
        initComponents();
        this.prod = obj;

        txt_Nome.setText(String.valueOf(prod.getNomeProduto()));
        txt_CodBarras.setText(String.valueOf(prod.getCodBarras()));
        cbx_Categoria.setSelectedItem(String.valueOf(prod.getCategoria()));
        txp_Descricao.setText(String.valueOf(prod.getDescricao()));
        txt_Preco.setText(String.format("%.2f", prod.getPreco()));
        cbx_TipoUnidade.setSelectedItem(String.valueOf(prod.getTipoUnidade()));
        txt_Quantidade.setText(String.valueOf(prod.getQuantidade()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_Nome = new javax.swing.JTextField();
        txt_CodBarras = new javax.swing.JTextField();
        txt_Preco = new javax.swing.JTextField();
        txt_Quantidade = new javax.swing.JTextField();
        lbl_Descricao = new javax.swing.JLabel();
        btn_Cancelar = new javax.swing.JButton();
        btn_Confirmar = new javax.swing.JButton();
        cbx_TipoUnidade = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txp_Descricao = new javax.swing.JTextPane();
        cbx_Categoria = new javax.swing.JComboBox<>();
        txt_DataValidade = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CadastroProdutos");

        txt_Nome.setBackground(new java.awt.Color(255, 255, 204));
        txt_Nome.setForeground(java.awt.Color.gray);
        txt_Nome.setText("NomeProduto");
        txt_Nome.setName("NomeProduto"); // NOI18N
        txt_Nome.setPreferredSize(new java.awt.Dimension(396, 30));
        txt_Nome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_Nome_focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_Nome_focusLost(evt);
            }
        });
        txt_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NomeActionPerformed(evt);
            }
        });

        txt_CodBarras.setBackground(new java.awt.Color(255, 255, 204));
        txt_CodBarras.setForeground(java.awt.Color.gray);
        txt_CodBarras.setText("CodBarras");
        txt_CodBarras.setName("CodBarras"); // NOI18N
        txt_CodBarras.setPreferredSize(new java.awt.Dimension(208, 30));
        txt_CodBarras.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_CodBarras_focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_CodBarras_focusLost(evt);
            }
        });
        txt_CodBarras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_CodBarras_keyTyped(evt);
            }
        });

        txt_Preco.setBackground(new java.awt.Color(255, 255, 204));
        txt_Preco.setForeground(java.awt.Color.gray);
        txt_Preco.setText("Preco");
        txt_Preco.setName("Preco"); // NOI18N
        txt_Preco.setPreferredSize(new java.awt.Dimension(108, 30));
        txt_Preco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_Preco_focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_Preco_focusLost(evt);
            }
        });
        txt_Preco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_Preco_keyTyped(evt);
            }
        });

        txt_Quantidade.setBackground(new java.awt.Color(255, 255, 204));
        txt_Quantidade.setForeground(java.awt.Color.gray);
        txt_Quantidade.setText("Quantidade");
        txt_Quantidade.setName("Quantidade"); // NOI18N
        txt_Quantidade.setPreferredSize(new java.awt.Dimension(108, 30));
        txt_Quantidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_Quantidade_focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_Quantidade_focusLost(evt);
            }
        });
        txt_Quantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_Quantidade_keyTyped(evt);
            }
        });

        btn_Cancelar.setText("CANCELAR");
        btn_Cancelar.setPreferredSize(new java.awt.Dimension(180, 30));
        btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarActionPerformed(evt);
            }
        });

        btn_Confirmar.setText("CONFIRMAR");
        btn_Confirmar.setPreferredSize(new java.awt.Dimension(180, 30));
        btn_Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ConfirmarActionPerformed(evt);
            }
        });

        cbx_TipoUnidade.setBackground(new java.awt.Color(255, 255, 204));
        cbx_TipoUnidade.setForeground(java.awt.Color.gray);
        cbx_TipoUnidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TIPO_UNIDADE", "KG", "L", "M", "UNI", "PC", "CX", "PCT" }));
        cbx_TipoUnidade.setPreferredSize(new java.awt.Dimension(108, 30));

        txp_Descricao.setForeground(java.awt.Color.lightGray);
        txp_Descricao.setText("Descricao");
        txp_Descricao.setName("Descricao"); // NOI18N
        txp_Descricao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txp_Descricao_focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txp_Descricao_focusLost(evt);
            }
        });
        jScrollPane1.setViewportView(txp_Descricao);

        cbx_Categoria.setForeground(java.awt.Color.lightGray);
        cbx_Categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CATEGORIA", "ALIMENTOS", "MODA", "ELETRONICOS", "CUIDADOS_PESSOAIS", "CASA_DECORACAO", "SAUDE", "JARDIM", "BRINQUEDOS", "ESPORTES" }));

        txt_DataValidade.setDateFormatString("dd/MM/yyyy");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_Nome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cbx_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txt_CodBarras, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_Preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(cbx_TipoUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(txt_Quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_DataValidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_Descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(txt_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_CodBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(cbx_Categoria))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_Quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_Preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbx_TipoUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_Descricao, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(txt_DataValidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_Nome_focusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_Nome_focusGained
        // TODO add your handling code here:
        Validador.verificaVazio(txt_Nome, lbl_Descricao);
    }//GEN-LAST:event_txt_Nome_focusGained

    private void txt_Nome_focusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_Nome_focusLost
        // TODO add your handling code here:
        Validador.verificaVazio(txt_Nome, lbl_Descricao);
    }//GEN-LAST:event_txt_Nome_focusLost

    private void txt_CodBarras_focusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_CodBarras_focusGained
        // TODO add your handling code here:
        Validador.verificaVazio(txt_CodBarras, lbl_Descricao);
    }//GEN-LAST:event_txt_CodBarras_focusGained

    private void txt_CodBarras_focusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_CodBarras_focusLost
        // TODO add your handling code here:
        Validador.verificaVazio(txt_CodBarras, lbl_Descricao);
    }//GEN-LAST:event_txt_CodBarras_focusLost

    private void txp_Descricao_focusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txp_Descricao_focusGained
        // TODO add your handling code here:
        if (txp_Descricao.getText().equals(txp_Descricao.getName())) {
            txp_Descricao.setText("");
            txp_Descricao.setForeground(Color.black);
            lbl_Descricao.setText("Digite o " + txp_Descricao.getName());
        }
    }//GEN-LAST:event_txp_Descricao_focusGained

    private void txp_Descricao_focusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txp_Descricao_focusLost
        // TODO add your handling code here:
        if (txp_Descricao.getText().trim().equals("")) {
            txp_Descricao.setForeground(Color.lightGray);
            txp_Descricao.setText(txp_Descricao.getName());
            lbl_Descricao.setText("");
        }
    }//GEN-LAST:event_txp_Descricao_focusLost

    private void txt_Preco_focusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_Preco_focusGained
        // TODO add your handling code here:
        Validador.verificaVazio(txt_Preco, lbl_Descricao);
    }//GEN-LAST:event_txt_Preco_focusGained

    private void txt_Preco_focusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_Preco_focusLost
        // TODO add your handling code here:
        Validador.verificaVazio(txt_Preco, lbl_Descricao);
    }//GEN-LAST:event_txt_Preco_focusLost

    private void txt_Quantidade_focusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_Quantidade_focusGained
        // TODO add your handling code here:
        Validador.verificaVazio(txt_Quantidade, lbl_Descricao);
    }//GEN-LAST:event_txt_Quantidade_focusGained

    private void txt_Quantidade_focusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_Quantidade_focusLost
        // TODO add your handling code here:
        Validador.verificaVazio(txt_Quantidade, lbl_Descricao);
    }//GEN-LAST:event_txt_Quantidade_focusLost

    private void txt_CodBarras_keyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CodBarras_keyTyped
        // TODO add your handling code here:
        Validador.verificaCodigoBarra(evt, lbl_Descricao, txt_CodBarras);
    }//GEN-LAST:event_txt_CodBarras_keyTyped

    private void txt_Preco_keyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Preco_keyTyped
        // TODO add your handling code here:
        Validador.verificaPreco(evt, lbl_Descricao, txt_Preco);
    }//GEN-LAST:event_txt_Preco_keyTyped

    private void txt_Quantidade_keyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Quantidade_keyTyped
        // TODO add your handling code here:
        Validador.verificaNumero(evt, lbl_Descricao, txt_Quantidade);
    }//GEN-LAST:event_txt_Quantidade_keyTyped

    private void btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_CancelarActionPerformed

    private void btn_ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ConfirmarActionPerformed
        // TODO add your handling code here:
        if (Validador.verificaObrigatorioProduto(txt_Nome, txt_CodBarras, txt_Preco, txt_Quantidade, cbx_TipoUnidade)) {
            if (txt_DataValidade.getDate() != null) {
                if (prod != null) {
                    String nome = txt_Nome.getText().trim();
                    String codBarra = txt_CodBarras.getText().trim();
                    String categoria = cbx_Categoria.getSelectedItem().toString();
                    String descricao = txp_Descricao.getText().trim();
                    float preco = Float.parseFloat(txt_Preco.getText());
                    String tipoUnidade = cbx_TipoUnidade.getSelectedItem().toString();
                    int quantidade = Integer.parseInt(txt_Quantidade.getText().trim());
                    Date dataValidade = (txt_DataValidade.getDate());

                    prod.setNomeProduto(nome);
                    prod.setCodBarras(codBarra);
                    prod.setCategoria(categoria);
                    prod.setDescricao(descricao);
                    prod.setPreco(preco);
                    prod.setTipoUnidade(tipoUnidade);
                    prod.setQuantidade(quantidade);
                    prod.setDataValidade(dataValidade);

                    boolean retorno = ProdutoDAO.alterar(prod);

                    if (retorno) {
                        JOptionPane.showMessageDialog(rootPane, "Sucesso!");
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Falha!");
                    }

                } else {

                    //Modo de cadastro:
                    // 1 - recupero os dados
                    String nome = txt_Nome.getText().trim();
                    String codBarra = txt_CodBarras.getText().trim();
                    String categoria = cbx_Categoria.getSelectedItem().toString();
                    String descricao = txp_Descricao.getText().trim();
                    float preco = Float.parseFloat(txt_Preco.getText());
                    String tipoUnidade = cbx_TipoUnidade.getSelectedItem().toString();
                    int quantidade = Integer.parseInt(txt_Quantidade.getText().trim());
                    Date dataValidade = (txt_DataValidade.getDate());

                    // 2 - crio o objeto da nota fiscal e passo os valores
                    Produto novoProduto = new Produto(nome, tipoUnidade, categoria, descricao, codBarra, quantidade, dataValidade, preco);

                    // 3 - passar o objeto para o banco
                    boolean retorno = ProdutoDAO.salvar(novoProduto);

                    if (retorno) {
                        JOptionPane.showMessageDialog(rootPane, "Sucesso!");
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Falha!");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Selecione uma data");
            }
        }
    }//GEN-LAST:event_btn_ConfirmarActionPerformed

    private void txt_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JButton btn_Confirmar;
    private javax.swing.JComboBox<String> cbx_Categoria;
    private javax.swing.JComboBox<String> cbx_TipoUnidade;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Descricao;
    private javax.swing.JTextPane txp_Descricao;
    private javax.swing.JTextField txt_CodBarras;
    private com.toedter.calendar.JDateChooser txt_DataValidade;
    private javax.swing.JTextField txt_Nome;
    private javax.swing.JTextField txt_Preco;
    private javax.swing.JTextField txt_Quantidade;
    // End of variables declaration//GEN-END:variables
}
